# To create the conda environment, run:
#   conda env create -f environment.yml
name: lg-chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.3
  - ipython=9.1.0
  - python-dotenv=1.1.0
  - langchain=0.3.25
  - langsmith=0.3.39
  - grandalf=0.7
  - pip
  - pip:
      - langgraph=0.4.7
      - langchain_openai=0.3.18
      - autopep8
      - flake8
      - "-e ."
