# To create the conda environment, run:
#   conda env create -f environment.yml
name: lg-chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13.3
  - python=dotenv-1.1.0
  - langgraph=0.4.4
  - langsmith=0.3.39
  - langchain=0.3.25
  - pip
  - pip:
      - autopep8
      - flake8
      - "-e ."
